title: Paraqeet
description: A Jekyll theme for building websites with Bootstrap
baseurl: "/paraqeet"
url: "https://signified.github.io"

sass:
  style: compressed

exclude:
  - LICENSE
  - README.md
  - paraqeet.gemspec
  - Rakefile
